services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  django:
    build: .
    volumes:
      - .:/usr/local/src/cats_project
    ports:
      - 8080:8080
    depends_on:
      - postgres
volumes:
  postgres_data:
